package cn.bossma.springdemo.mybatis.mapper;

import cn.bossma.springdemo.mybatis.model.Product;
import cn.bossma.springdemo.mybatis.model.ProductExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Options;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.session.RowBounds;

public interface ProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PRODUCT
     *
     * @mbg.generated Sat Jul 09 16:34:28 CST 2022
     */
    long countByExample(ProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PRODUCT
     *
     * @mbg.generated Sat Jul 09 16:34:28 CST 2022
     */
    int deleteByExample(ProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PRODUCT
     *
     * @mbg.generated Sat Jul 09 16:34:28 CST 2022
     */
    @Delete({
        "delete from T_PRODUCT",
        "where ID = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PRODUCT
     *
     * @mbg.generated Sat Jul 09 16:34:28 CST 2022
     */
    @Insert({
        "insert into T_PRODUCT (NAME, DESC, ",
        "PRICE, ",
        "CREATE_TIME, UPDATE_TIME)",
        "values (#{name,jdbcType=VARCHAR}, #{description,jdbcType=VARCHAR}, ",
        "#{price,jdbcType=BIGINT,typeHandler=cn.bossma.springdemo.mybatis.handler.MoneyTypeHandler}, ",
        "#{createTime,jdbcType=TIMESTAMP}, #{updateTime,jdbcType=TIMESTAMP})"
    })
    @Options(useGeneratedKeys=true,keyProperty="id")
    int insert(Product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PRODUCT
     *
     * @mbg.generated Sat Jul 09 16:34:28 CST 2022
     */
    int insertSelective(Product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PRODUCT
     *
     * @mbg.generated Sat Jul 09 16:34:28 CST 2022
     */
    List<Product> selectByExampleWithRowbounds(ProductExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PRODUCT
     *
     * @mbg.generated Sat Jul 09 16:34:28 CST 2022
     */
    List<Product> selectByExample(ProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PRODUCT
     *
     * @mbg.generated Sat Jul 09 16:34:28 CST 2022
     */
    @Select({
        "select",
        "ID, NAME, DESC, PRICE, CREATE_TIME, UPDATE_TIME",
        "from T_PRODUCT",
        "where ID = #{id,jdbcType=BIGINT}"
    })
    @ResultMap("cn.bossma.springdemo.mybatis.mapper.ProductMapper.BaseResultMap")
    Product selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PRODUCT
     *
     * @mbg.generated Sat Jul 09 16:34:28 CST 2022
     */
    int updateByExampleSelective(@Param("record") Product record, @Param("example") ProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PRODUCT
     *
     * @mbg.generated Sat Jul 09 16:34:28 CST 2022
     */
    int updateByExample(@Param("record") Product record, @Param("example") ProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PRODUCT
     *
     * @mbg.generated Sat Jul 09 16:34:28 CST 2022
     */
    int updateByPrimaryKeySelective(Product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PRODUCT
     *
     * @mbg.generated Sat Jul 09 16:34:28 CST 2022
     */
    @Update({
        "update T_PRODUCT",
        "set NAME = #{name,jdbcType=VARCHAR},",
          "DESC = #{description,jdbcType=VARCHAR},",
          "PRICE = #{price,jdbcType=BIGINT,typeHandler=cn.bossma.springdemo.mybatis.handler.MoneyTypeHandler},",
          "CREATE_TIME = #{createTime,jdbcType=TIMESTAMP},",
          "UPDATE_TIME = #{updateTime,jdbcType=TIMESTAMP}",
        "where ID = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(Product record);
}