package cn.bossma.springdemo.mybatismysql.mapper;

import cn.bossma.springdemo.mybatismysql.model.BaseProduct;
import cn.bossma.springdemo.mybatismysql.model.BaseProductExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.session.RowBounds;

public interface BaseProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product
     *
     * @mbg.generated Sat Jul 09 21:37:39 CST 2022
     */
    long countByExample(BaseProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product
     *
     * @mbg.generated Sat Jul 09 21:37:39 CST 2022
     */
    int deleteByExample(BaseProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product
     *
     * @mbg.generated Sat Jul 09 21:37:39 CST 2022
     */
    @Delete({
        "delete from t_product",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product
     *
     * @mbg.generated Sat Jul 09 21:37:39 CST 2022
     */
    @Insert({
        "insert into t_product (`name`, price, ",
        "`desc`, create_time, ",
        "update_time)",
        "values (#{name,jdbcType=VARCHAR}, #{price,jdbcType=BIGINT,typeHandler=cn.bossma.springdemo.mybatismysql.handler.MoneyTypeHandler}, ",
        "#{description,jdbcType=VARCHAR}, #{createTime,jdbcType=TIMESTAMP}, ",
        "#{updateTime,jdbcType=TIMESTAMP})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Long.class)
    int insert(BaseProduct row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product
     *
     * @mbg.generated Sat Jul 09 21:37:39 CST 2022
     */
    int insertSelective(BaseProduct row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product
     *
     * @mbg.generated Sat Jul 09 21:37:39 CST 2022
     */
    List<BaseProduct> selectByExampleWithRowbounds(BaseProductExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product
     *
     * @mbg.generated Sat Jul 09 21:37:39 CST 2022
     */
    List<BaseProduct> selectByExample(BaseProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product
     *
     * @mbg.generated Sat Jul 09 21:37:39 CST 2022
     */
    @Select({
        "select",
        "id, `name`, price, `desc`, create_time, update_time",
        "from t_product",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @ResultMap("cn.bossma.springdemo.mybatismysql.mapper.BaseProductMapper.BaseResultMap")
    BaseProduct selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product
     *
     * @mbg.generated Sat Jul 09 21:37:39 CST 2022
     */
    int updateByExampleSelective(@Param("row") BaseProduct row, @Param("example") BaseProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product
     *
     * @mbg.generated Sat Jul 09 21:37:39 CST 2022
     */
    int updateByExample(@Param("row") BaseProduct row, @Param("example") BaseProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product
     *
     * @mbg.generated Sat Jul 09 21:37:39 CST 2022
     */
    int updateByPrimaryKeySelective(BaseProduct row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product
     *
     * @mbg.generated Sat Jul 09 21:37:39 CST 2022
     */
    @Update({
        "update t_product",
        "set `name` = #{name,jdbcType=VARCHAR},",
          "price = #{price,jdbcType=BIGINT,typeHandler=cn.bossma.springdemo.mybatismysql.handler.MoneyTypeHandler},",
          "`desc` = #{description,jdbcType=VARCHAR},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "update_time = #{updateTime,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(BaseProduct row);
}